/**
 * Seed a test page with all 19 section types directly via DB.
 * Run: npx tsx scripts/seed-test-page.ts
 */
import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

import { db, client } from '../lib/db/client';
import { pages } from '../lib/db/schema';

const TEST_SECTIONS = [
  { id: 's-heading-page', type: 'heading-page', title: { en: 'Section Showcase', fr: 'Vitrine des sections' } },
  { id: 's-heading-content', type: 'heading-content', title: { en: 'How it all started', fr: 'Comment tout a commencé' }, category: { en: 'recipe', fr: 'recette' }, date: '10.05.2026' },
  { id: 's-heading-articles', type: 'heading-articles', title: { en: 'Stories', fr: 'Récits' }, tabs: [{ label: { en: 'All (07)', fr: 'Tous (07)' } }, { label: { en: 'Articles (04)', fr: 'Articles (04)' } }, { label: { en: 'Recipes (03)', fr: 'Recettes (03)' } }] },
  { id: 's-quote', type: 'quote', text: { en: '\u201cA brief message about the story, ordering. A brief message about the story.\u201d', fr: '\u00abUn bref message sur l\u2019histoire, la commande. Un bref message sur l\u2019histoire.\u00bb' } },
  { id: 's-text', type: 'text', title: { en: 'Title', fr: 'Titre' }, body: { en: 'A brief message about the story, ordering. A brief message about the story, ordering.\n\nA brief message about the story, ordering.', fr: 'Un bref message sur l\u2019histoire, la commande.\n\nUn bref message sur l\u2019histoire, la commande.' } },
  { id: 's-instructions', type: 'instructions', title: { en: 'Instructions', fr: 'Instructions' }, steps: [{ en: 'Preheat oven to 350\u00b0F. Line a baking sheet with parchment paper.', fr: 'Pr\u00e9chauffer le four \u00e0 180\u00b0C. Tapisser une plaque de papier parchemin.' }, { en: 'Mix dry ingredients in a large bowl. Add wet ingredients and stir until combined.', fr: 'M\u00e9langer les ingr\u00e9dients secs. Ajouter les ingr\u00e9dients humides.' }, { en: 'Bake for 25 minutes until golden. Let cool on a wire rack.', fr: 'Cuire 25 minutes jusqu\u2019\u00e0 dor\u00e9. Laisser refroidir sur une grille.' }] },
  { id: 's-two-col', type: 'two-column-text', title: { en: 'Our Philosophy', fr: 'Notre philosophie' }, columnLeft: { en: 'We believe in seasonal ingredients, sourced locally whenever possible. Every pastry tells a story of the land it comes from.\n\nOur kitchen is a place of experimentation and joy.', fr: 'Nous croyons aux ingr\u00e9dients de saison, locaux autant que possible. Chaque p\u00e2tisserie raconte une histoire.\n\nNotre cuisine est un lieu d\u2019exp\u00e9rimentation et de joie.' }, columnRight: { en: 'From the first strawberries of June to the last apples of November, we follow the rhythm of Quebec\u2019s harvests.\n\nNothing is wasted. Everything is transformed.', fr: 'Des premi\u00e8res fraises de juin aux derni\u00e8res pommes de novembre, nous suivons le rythme des r\u00e9coltes.\n\nRien n\u2019est gaspill\u00e9. Tout est transform\u00e9.' } },
  { id: 's-steps', type: 'steps', steps: [{ label: { en: '01', fr: '01' }, body: { en: 'Source the finest seasonal ingredients from local farms and producers.', fr: 'S\u2019approvisionner en ingr\u00e9dients de saison aupr\u00e8s de fermes locales.' } }, { label: { en: '02', fr: '02' }, body: { en: 'Craft each recipe with care, balancing tradition and innovation.', fr: '\u00c9laborer chaque recette avec soin, entre tradition et innovation.' } }, { label: { en: '03', fr: '03' }, body: { en: 'Share the result with our community every Saturday morning.', fr: 'Partager le r\u00e9sultat avec notre communaut\u00e9 chaque samedi matin.' } }],
  },
  { id: 's-faq-simple', type: 'faq-simple', title: { en: 'FAQs', fr: 'FAQ' }, items: [{ question: { en: 'What are your opening hours?', fr: 'Quelles sont vos heures d\u2019ouverture?' }, answer: { en: 'We are open Saturdays from 9am to 12pm for pickup orders placed in advance on our website.', fr: 'Nous sommes ouverts les samedis de 9h \u00e0 12h pour les commandes pass\u00e9es \u00e0 l\u2019avance.' } }, { question: { en: 'Do you offer delivery?', fr: 'Offrez-vous la livraison?' }, answer: { en: 'We offer delivery for catering orders only. Regular orders are pickup only.', fr: 'Nous offrons la livraison pour les commandes traiteur seulement.' } }, { question: { en: 'Can I place a custom cake order?', fr: 'Puis-je commander un g\u00e2teau sur mesure?' }, answer: { en: 'Yes! Visit our cake ordering page to customize your order.', fr: 'Oui! Visitez notre page de commande de g\u00e2teaux.' } }] },
  { id: 's-faq-grouped', type: 'faq-grouped', title: { en: 'FAQs', fr: 'FAQ' }, groups: [{ heading: { en: 'Ordering', fr: 'Commandes' }, items: [{ question: { en: 'How far in advance should I order?', fr: 'Combien de temps \u00e0 l\u2019avance dois-je commander?' }, answer: { en: 'We recommend ordering at least 48 hours in advance.', fr: 'Nous recommandons de commander au moins 48 heures \u00e0 l\u2019avance.' } }] }, { heading: { en: 'Catering', fr: 'Traiteur' }, items: [{ question: { en: 'What is the minimum order for catering?', fr: 'Quel est le minimum pour le traiteur?' }, answer: { en: 'Minimum orders vary by product. Check our catering page for details.', fr: 'Les minimums varient selon le produit. Consultez notre page traiteur.' } }] }] },
  { id: 's-image-hero', type: 'image-hero', image: { url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1440&h=828&fit=crop', alt: { en: 'Hero image', fr: 'Image h\u00e9ro' } } },
  { id: 's-image-2up', type: 'image-2up', images: [{ url: 'https://images.unsplash.com/photo-1486427944544-d2c246c4df4e?w=700&h=805&fit=crop', alt: { en: 'Left', fr: 'Gauche' } }, { url: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=700&h=805&fit=crop', alt: { en: 'Right', fr: 'Droite' } }] },
  { id: 's-image-carousel', type: 'image-carousel', title: { en: 'VISIT US', fr: 'VISITEZ-NOUS' }, description: { en: 'Come discover our new space on rue Charlevoix.', fr: 'Venez d\u00e9couvrir notre nouvel espace sur la rue Charlevoix.' }, images: [{ url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=200&h=200&fit=crop', alt: { en: '1', fr: '1' } }, { url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=200&h=200&fit=crop', alt: { en: '2', fr: '2' } }, { url: 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=600&h=644&fit=crop', alt: { en: '3', fr: '3' }, caption: { en: 'fig. 03 \u2013 friends having a drink', fr: 'fig. 03 \u2013 amis prenant un verre' } }] },
  { id: 's-image-icons', type: 'image-with-icons', backgroundImage: { url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1440&h=816&fit=crop', alt: { en: 'Background', fr: 'Arri\u00e8re-plan' } }, overlayImage: { url: '', alt: { en: '', fr: '' } } },
  { id: 's-content-brief', type: 'content-brief', title: { en: 'Featured', fr: 'En vedette' }, items: [{ image: { url: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=418&h=522&fit=crop', alt: { en: '1', fr: '1' } }, label: { en: '01.', fr: '01.' }, body: { en: 'Seasonal strawberry tart with cr\u00e8me p\u00e2tissi\u00e8re and fresh mint.', fr: 'Tarte aux fraises de saison avec cr\u00e8me p\u00e2tissi\u00e8re et menthe fra\u00eeche.' } }, { image: { url: 'https://images.unsplash.com/photo-1486427944544-d2c246c4df4e?w=418&h=522&fit=crop', alt: { en: '2', fr: '2' } }, label: { en: '02.', fr: '02.' }, body: { en: 'Dark chocolate mousse with salted caramel and hazelnut praline.', fr: 'Mousse au chocolat noir avec caramel sal\u00e9 et pralin\u00e9 noisette.' } }, { image: { url: 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=418&h=522&fit=crop', alt: { en: '3', fr: '3' } }, label: { en: '03.', fr: '03.' }, body: { en: 'Lemon verbena panna cotta with Quebec blueberry compote.', fr: 'Panna cotta \u00e0 la verveine citronnelle avec compote de bleuets.' } }] },
  { id: 's-content-journal', type: 'content-journal', title: { en: 'Latest Journal', fr: 'Dernier journal' }, maxEntries: 3 },
  { id: 's-content-2up', type: 'content-2up', title: { en: 'More', fr: 'Plus' }, source: 'journal' as const, maxEntries: 2 },
  { id: 's-image-text', type: 'image-with-text', image: { url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=438&h=529&fit=crop', alt: { en: 'Image', fr: 'Image' } }, title: { en: 'Our Space', fr: 'Notre espace' }, body: { en: 'A warm, inviting space where pastry meets community. Come visit us on Saturdays.', fr: 'Un espace chaleureux o\u00f9 la p\u00e2tisserie rencontre la communaut\u00e9. Visitez-nous les samedis.' }, backgroundColor: '#CB9EC9' },
  { id: 's-contact', type: 'contact-form', title: { en: 'Contact Us', fr: 'Contactez-nous' }, phone: { en: '514 123 4567', fr: '514 123 4567' }, email: { en: 'rhubarbe@rhubarbe.ca', fr: 'rhubarbe@rhubarbe.ca' }, socialLinks: { en: 'INSTAGRAM\nTIKTOK\nFACEBOOK', fr: 'INSTAGRAM\nTIKTOK\nFACEBOOK' } },
];

async function seed() {
  console.log('Seeding test-sections page...');
  await db
    .insert(pages)
    .values({ pageName: 'test-sections', content: { sections: TEST_SECTIONS }, updatedAt: new Date() })
    .onConflictDoUpdate({ target: pages.pageName, set: { content: { sections: TEST_SECTIONS }, updatedAt: new Date() } });
  console.log('✅ Done — visit /admin/pages/test-sections to edit, /p/test-sections to view');
  await client.end();
}

seed().catch((e) => { console.error('❌', e); process.exit(1); });
