api_version = "2024-04"

[[extensions]]
type = "ui_extension"
name = "Pickup Details"
handle = "pickup-details"

  [[extensions.targeting]]
  module = "./src/Checkout.tsx"
  target = "purchase.checkout.block.render"
